_debug: True

COHORT: 'CPSII_40X'
# COHORT: 'NiceExamplesForMuTILsPreprint'
# COHORT: 'TCGA_BRCA'
# COHORT: 'CPS3_40X'
# COHORT: 'plco_breast'
# COHORT: 'NHS_breast'

N_SUBSETS: 1

# Paths
slides_path: '/data/akos/mutils/mutils_input/CPSII_40X'
base_savedir: '/data/akos/mutils/mutils_output/CPSII_40X'
model_paths:
  mutils_06022021-fold1: '/data/akos/mutils/mutils_models/fold_1/mutils_06022021_fold1.pt'
  mutils_06022021-fold2: '/data/akos/mutils/mutils_models/fold_2/mutils_06022021_fold2.pt'
  mutils_06022021-fold3: '/data/akos/mutils/mutils_models/fold_3/mutils_06022021_fold3.pt'
  mutils_06022021-fold4: '/data/akos/mutils/mutils_models/fold_4/mutils_06022021_fold4.pt'
  mutils_06022021-fold5: '/data/akos/mutils/mutils_models/fold_5/mutils_06022021_fold5.pt'

model_configs: 'panoptic_model_configs.py'

restrict_to_vta: False

save_wsi_mask: True
save_annotations: False
save_nuclei_meta: True
save_nuclei_props: True

roi_side_hres: 1024
discard_edge_hres: 0

## ----------------------------------------------------------------
## Use the following parameters to run the full cTME pipeline
## ----------------------------------------------------------------
grandch: False
topk_rois: null
topk_rois_sampling_mode: "stratified"
topk_salient_rois: null

gcpaths: null
vlres_scorer_kws: null

## ----------------------------------------------------------------
## Use the following parameters to run the Grand challenge pipeline
## ----------------------------------------------------------------
# grandch: True
# topk_rois: 300
# topk_rois_sampling_mode: "weighted"
# topk_salient_rois: 300

# gcpaths:
#   roilocs_in: '/data/akos/mutils/mutils_input/regions-of-interest.json'
#   cta2vta: '/home/lit7907/repos/cTME/Calibrations.json'
#   roilocs_out: '/data/akos/mutils/mutils_output/regions-of-interest.json'
#   result_file: '/data/akos/mutils/mutils_output/results.json'
#   tilscore_file: '/data/akos/mutils/mutils_output/til-score.json'
#   detect_file: '/data/akos/mutils/mutils_output/detected-lymphocytes.json'
#   wsi_mask: '/data/akos/mutils/mutils_output/images/segmented-stroma'
# vlres_scorer_kws:
#   check_tissue: True
#   tissue_percent: 25
#   pixel_overlap: 0

## ----------------------------------------------------------------
## Use cohort specific parameters if running TCGA_BRCA or CPS3_40X
## ----------------------------------------------------------------
# data_file_path: '/home/lit7907/repos/cTME/data/tcga-clinical/PRIVATE_RSalgado_TCGA_TILScores.csv'
# data_file_path: '/home/lit7907/repos/cTME/data/acs-clinical/CPSII_BRCA_FacilityIDs_20210331.csv'